<?php get_header(); ?>
<main>
	<section class="hero hero-editorial">
		<div class="container hero-editorial-grid">
			<div class="hero-copy-block">
				<span class="eyebrow">America's independent pet-home authority</span>
				<h1>Make smarter choices.<br><span>Live better</span> every day.</h1>
				<p class="hero-copy">Clear buying guides, comparisons, and practical advice for cleaner homes, happier pets, and less buyer's remorse.</p>
				<div class="button-row"><a class="button" href="#guides">Explore buying guides <span aria-hidden="true">→</span></a><a class="button button-secondary" href="#categories">Browse categories</a></div>
				<div class="trust-row"><span><i class="dashicons dashicons-shield"></i> Independent &amp; research-first</span><span><i class="dashicons dashicons-yes-alt"></i> Clear, honest guidance</span><span><i class="dashicons dashicons-lock"></i> Transparent disclosures</span></div>
			</div>
			<div class="hero-feature-card">
				<div class="hero-feature-image"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/hero-pet-home.png' ); ?>" alt="Golden retriever relaxing beside a robot vacuum in a modern home"><span class="score-badge">Editor's pick</span></div>
				<div class="hero-feature-content"><div class="feature-kicker">Featured guide · Smart cleaning</div><h2>Robot vacuums that keep up with real pet hair</h2><p>Compare the details that matter when paws, fur, and flooring meet every day.</p><div class="feature-bottom"><strong><span class="score-number">9.2</span>/10 <small>ScoutScore</small></strong><a class="button" href="<?php echo esc_url( home_url( '/robot-vacuums-for-pet-hair/' ) ); ?>">Read guide <span aria-hidden="true">→</span></a></div></div>
			</div>
		</div>
	</section>

	<section class="category-rail" id="categories"><div class="container"><div class="section-label"><span>Explore categories</span><a href="<?php echo esc_url( home_url( '/categories/' ) ); ?>">View all <span aria-hidden="true">→</span></a></div><div class="category-grid">
		<?php $categories = array( array( 'dashicons-vacuum-cleaner', 'Robot vacuums', 'Smarter cleaning for every home.' , '/robot-vacuums-for-pet-hair/' ), array( 'dashicons-pets', 'Pet tech', 'Care and comfort for your pets.', '/smart-tech/' ), array( 'dashicons-admin-home', 'Smart home', 'Automate and control your home.', '/family-home/' ), array( 'dashicons-shield', 'Dog safety', 'Protect what matters most.', '/dog-safety-tech/' ), array( 'dashicons-heart', 'Pet insurance', 'Plan for the unexpected.', '/services-insurance/' ), array( 'dashicons-admin-tools', 'Cleaning', 'Tackle fur, stains, and odor.', '/cleaning-odor/' ) ); foreach ( $categories as $category ) : ?><a class="category-card" href="<?php echo esc_url( home_url( $category[3] ) ); ?>"><span class="category-icon dashicons <?php echo esc_attr( $category[0] ); ?>" aria-hidden="true"></span><strong><?php echo esc_html( $category[1] ); ?></strong><span><?php echo esc_html( $category[2] ); ?></span></a><?php endforeach; ?>
	</div></div></section>

	<section class="section section-picks" id="guides"><div class="container"><div class="section-label"><span>Editor's picks</span><a href="<?php echo esc_url( home_url( '/buying-guides/' ) ); ?>">View all picks <span aria-hidden="true">→</span></a></div><div class="pick-grid">
		<?php $picks = array( array( 'Robot vacuums', 'Roborock pet-hair guide', 'Best for automated floor care.', '9.2' ), array( 'Pet tech', 'The calm-home camera guide', 'Better ways to check in from anywhere.', '8.9' ), array( 'Smart home', 'Pet-safe entry systems', 'Simple control for everyday routines.', '8.8' ), array( 'Cleaning', 'Air quality for cat homes', 'Fresh-feeling rooms without guesswork.', '8.6' ) ); foreach ( $picks as $index => $pick ) : ?><article class="pick-card"><div class="pick-image pick-image-<?php echo esc_attr( $index + 1 ); ?>"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/hero-pet-home.png' ); ?>" alt="" loading="lazy"><span class="rank-number"><?php echo esc_html( $index + 1 ); ?></span><span class="pick-score"><?php echo esc_html( $pick[3] ); ?><small>score</small></span></div><div class="pick-body"><span class="tag"><?php echo esc_html( $pick[0] ); ?></span><h3><a href="#"><?php echo esc_html( $pick[1] ); ?></a></h3><p><?php echo esc_html( $pick[2] ); ?></p></div></article><?php endforeach; ?>
	</div></div></section>

	<section class="section section-lists"><div class="container editorial-lists"><div class="list-column"><div class="section-label"><span>Latest reviews</span><a href="#">View all <span aria-hidden="true">→</span></a></div><?php $reviews = array( 'Robot vacuums for dog hair', 'Pet cameras for anxious dogs', 'How to reduce litter tracking' ); foreach ( $reviews as $review ) : ?><a class="list-item" href="#"><span class="list-thumb dashicons dashicons-media-document"></span><span><strong><?php echo esc_html( $review ); ?></strong><small>Practical takeaways for real households</small></span><b>→</b></a><?php endforeach; ?></div><div class="list-column"><div class="section-label"><span>Buying guides</span><a href="#">View all <span aria-hidden="true">→</span></a></div><?php $guides = array( 'Best robot vacuum features for pet owners', 'A calmer smart home starter guide', 'Pet insurance questions to ask first' ); foreach ( $guides as $guide ) : ?><a class="list-item" href="#"><span class="list-thumb dashicons dashicons-book-alt"></span><span><strong><?php echo esc_html( $guide ); ?></strong><small>Decision support without the jargon</small></span><b>→</b></a><?php endforeach; ?></div><div class="list-column"><div class="section-label"><span>Popular comparisons</span><a href="#">View all <span aria-hidden="true">→</span></a></div><?php $comparisons = array( array( 'Roborock pet-hair guide', 'Narwal cleaning guide' ), array( 'GPS collar', 'Wireless dog fence' ), array( 'Chewy', 'Wayfair' ) ); foreach ( $comparisons as $comparison ) : ?><a class="compare-item" href="#"><span class="compare-pill dashicons dashicons-randomize"></span><strong><?php echo esc_html( $comparison[0] ); ?></strong><b>VS</b><strong><?php echo esc_html( $comparison[1] ); ?></strong></a><?php endforeach; ?></div></div></section>

	<section class="trust-section"><div class="container trust-grid"><div><span class="eyebrow">Our standard</span><h2>Helpful first.<br>Commercially clear.</h2></div><div class="trust-copy"><p>We explain what matters, show the tradeoffs, and keep commercial relationships visible. No fake testing claims, no mystery rankings, and no pressure to buy.</p><a href="<?php echo esc_url( home_url( '/how-we-test/' ) ); ?>">How PetHomeScout works <span aria-hidden="true">→</span></a></div></div></section>
	<section class="newsletter"><div class="container newsletter-inner"><div><span class="newsletter-icon dashicons dashicons-email-alt" aria-hidden="true"></span><div><h2>Get smarter every week.</h2><p>New guides, useful comparisons, and pet-home ideas — straight to your inbox.</p></div></div><form class="newsletter-form" action="#" method="post"><label class="screen-reader-text" for="newsletter-email">Your email address</label><input id="newsletter-email" type="email" placeholder="Your email address"><button class="button" type="submit">Subscribe</button></form></div></section>
</main>
<?php get_footer(); ?>
