<?php get_header(); ?>
<main>
	<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">The pet-friendly home desk</span><h1>A cleaner, safer home for pets and family.</h1><p class="hero-copy">Independent buying guides, comparison tools, and service resources for American households with dogs and cats.</p><div class="button-row"><a class="button" href="#guides">Explore buying guides</a><a class="button button-secondary" href="#services">Find pet services</a></div></div><aside class="hero-card"><div class="hero-card-label"><span>Scout focus</span><span class="score">● Practical &amp; independent</span></div><h2>Find the right gear for the way your household actually lives.</h2><p>Compare pet-hair performance, maintenance, safety, and ownership costs in plain English.</p><a href="<?php echo esc_url( home_url( '/robot-vacuum-selector/' ) ); ?>">Try the Robot Vacuum Selector →</a></aside></div></section>
	<section class="section" id="guides"><div class="container"><div class="section-heading"><div><span class="eyebrow">Explore the desk</span><h2>Start with your biggest home problem.</h2></div><p>Focused guidance for the products, services, and decisions that make life with pets easier.</p></div><div class="card-grid">
		<?php $pillars = array( array( 'Robot vacuums', 'Pet hair, carpet, litter tracking, and maintenance.', '/robot-vacuums-for-pet-hair/' ), array( 'Cleaning & odor', 'Practical ways to manage fur, stains, and everyday smells.', '/pet-odor-cleaning/' ), array( 'Smart pet home', 'Feeders, fountains, litter boxes, doors, and connected tools.', '/smart-pet-home/' ), array( 'Dog safety tech', 'GPS collars, fences, gates, and escape-artist solutions.', '/dog-safety-tech/' ), array( 'Pet insurance', 'Understand coverage choices, exclusions, and quote questions.', '/pet-insurance/' ), array( 'Pet services', 'Find the right grooming, walking, sitting, or cleaning help.', '/pet-services/' ) ); foreach ( $pillars as $pillar ) : ?><a class="card" href="<?php echo esc_url( home_url( $pillar[2] ) ); ?>"><span class="card-icon" aria-hidden="true">✦</span><h3><?php echo esc_html( $pillar[0] ); ?></h3><p><?php echo esc_html( $pillar[1] ); ?></p></a><?php endforeach; ?>
	</div></div></section>
	<section class="section section-soft"><div class="container"><div class="section-heading"><div><span class="eyebrow">How we help</span><h2>Useful before you buy.</h2></div><p>Every guide should help you make a clearer next decision—not add more noise.</p></div><div class="trust-strip"><div class="trust-item"><strong>Compare the tradeoffs</strong><span>See what matters for hair, floors, pets, space, and maintenance.</span></div><div class="trust-item"><strong>Use a simple tool</strong><span>Start with your household details instead of a generic “best” list.</span></div><div class="trust-item"><strong>Know the fine print</strong><span>Affiliate relationships and future lead forms stay clearly disclosed.</span></div></div></div></section>
	<section class="section" id="services"><div class="container"><div class="section-heading"><div><span class="eyebrow">Local help</span><h2>When a product is not enough.</h2></div><p>Service resources for the jobs that need a qualified person on the other side.</p></div><div class="card-grid"><a class="card" href="<?php echo esc_url( home_url( '/mobile-dog-grooming/' ) ); ?>"><h3>Mobile dog grooming</h3><p>What to ask, what affects price, and whether an at-home appointment fits your dog.</p></a><a class="card" href="<?php echo esc_url( home_url( '/pet-odor-carpet-cleaning/' ) ); ?>"><h3>Pet odor carpet cleaning</h3><p>Know when DIY cleaning is enough and when professional equipment is worth it.</p></a><a class="card" href="<?php echo esc_url( home_url( '/pet-sitting/' ) ); ?>"><h3>Pet sitting &amp; walking</h3><p>Questions to ask providers before trusting someone with your routine.</p></a></div></div></section>
</main>
<?php get_footer(); ?>
