<?php get_header(); ?>
<main class="hub-page">
  <section class="hub-hero"><div class="container"><span class="eyebrow">Family Home</span><h1>Pet-Friendly Family Home &amp; Safety</h1><p>We analyze claw-proof fabrics, durable pet-friendly sofas, wooden flooring scratch ratings, and auto-closing dog gates.</p></div></section>
  <section class="section"><div class="container">
    <div class="filter-bar" data-hub-filter><button class="is-active" type="button" data-filter="all">All home products</button><button type="button" data-filter="furniture">Claw-proof sofas</button><button type="button" data-filter="flooring">Wood flooring</button><button type="button" data-filter="safety">Dog gates &amp; safety</button><button type="button" data-filter="crate">Smart crate systems</button></div>
    <div class="family-home-layout"><aside class="filter-panel"><h2>Filter options</h2><label><input type="checkbox" value="furniture" data-filter-category checked> Furniture</label><label><input type="checkbox" value="safety" data-filter-category checked> Safety gates</label><label><input type="checkbox" value="flooring" data-filter-category> Flooring</label><label><input type="checkbox" value="chewy" data-filter-merchant> Chewy</label><label><input type="checkbox" value="wayfair" data-filter-merchant> Wayfair</label></aside>
      <div><div class="section-label"><span>Recommended family home gear</span></div>
        <article class="family-product-card" data-product-tags="all furniture" data-product-category="furniture" data-merchants="chewy wayfair"><div class="family-product-art">▱</div><div><span class="tag">Editor's pick</span><span class="tag">Scratch-proof fabric</span><h2>Haven Claw-Resistant Velvet Sofa</h2><p>Tested in a three-cat household. High-density weave velvet resists claws, runs, tears, and pet stains.</p><div class="spec-grid"><span>Material <b>Double-weave velvet</b></span><span>Claw rating <b>9.8 / 10</b></span><span>Sofa length <b>84 inches</b></span><span>Warranty <b>3-year fabric cover</b></span></div><div class="buy-box"><strong>Compare partner prices</strong><button disabled>Chewy&nbsp; $649.99&nbsp; Check price</button><button disabled>Wayfair&nbsp; $629.50&nbsp; Check price</button></div></div></article>
        <article class="family-product-card" data-product-tags="all safety" data-product-category="safety" data-merchants="chewy wayfair"><div class="family-product-art">⌂</div><div><span class="tag">Safety pick</span><span class="tag">Pet-friendly entry</span><h2>Walk-Through Steel Safety Dog Gate</h2><p>Pressure-mounted gate fixture for separating pet zones while keeping everyday family movement simple.</p><div class="spec-grid"><span>Width range <b>29–39 inches</b></span><span>Lock type <b>One-hand latch</b></span><span>Finish <b>Powder-coated steel</b></span><span>Evidence <b>Research-led</b></span></div><div class="buy-box"><strong>Compare partner prices</strong><button disabled>Chewy&nbsp; Merchant pending</button><button disabled>Wayfair&nbsp; Merchant pending</button></div></div></article>
      </div>
    </div>
  </div></section>
</main>
<?php get_footer(); ?>
