<?php get_header(); $hub = pethomescout_hub_values( 'Smart technology', 'Pet Smart Technology & Smart Care', 'Compare robot vacuums, pet cameras, and connected-care fixtures by the household problem they actually solve.' ); $featured_products = pethomescout_hub_products( get_the_ID() ); $featured_guides = pethomescout_editorial_field( 'featured_guides', get_the_ID(), array() ); $featured_guides = is_array( $featured_guides ) ? array_filter( array_map( 'absint', $featured_guides ) ) : array(); ?>
<main class="hub-page">
  <section class="hub-hero"><div class="container"><span class="eyebrow"><?php echo esc_html( $hub['eyebrow'] ); ?></span><h1><?php echo esc_html( $hub['title'] ); ?></h1><p><?php echo esc_html( $hub['intro'] ); ?></p><div class="affiliate-disclosure-box"><strong>Affiliate disclosure:</strong> This page uses disabled internal <code>/go/</code> placeholders. PetHomeScout may earn compensation when approved commercial links go live.</div></div></section>
  <section class="section"><div class="container">
    <div class="filter-bar" data-hub-filter><button class="is-active" type="button" data-filter="all">All pet tech</button><button type="button" data-filter="vacuum">Robot vacuums</button><button type="button" data-filter="camera">Pet cameras</button><button type="button" data-filter="safety">GPS &amp; safety</button></div>
    <div class="family-home-layout"><aside class="filter-panel"><h2>Filter options</h2><label><input type="checkbox" value="vacuum" data-filter-category checked> Robot vacuums</label><label><input type="checkbox" value="camera" data-filter-category checked> Pet cameras</label><label><input type="checkbox" value="safety" data-filter-category> GPS collars</label><label><input type="checkbox" value="chewy" data-filter-merchant> Chewy</label><label><input type="checkbox" value="amazon" data-filter-merchant> Amazon</label></aside>
      <div><div class="section-label"><span>Recommended pet smart tech</span></div>
        <?php if ( ! empty( $featured_products ) ) : ?>
          <?php foreach ( $featured_products as $product_id ) : get_template_part( 'template-parts/cards/hub-product', null, array( 'product_id' => $product_id, 'icon' => '◉', 'comparison_url' => home_url( '/smart-tech-comparison/' ), 'service_url' => home_url( '/services-insurance/' ) ) ); endforeach; ?>
        <?php elseif ( ! empty( $featured_guides ) ) : ?>
          <?php foreach ( $featured_guides as $guide_id ) : $guide = get_post( $guide_id ); if ( ! $guide ) { continue; } $evidence = pethomescout_get_product_evidence( $guide_id ); ?>
            <article class="family-product-card" data-product-tags="all" data-product-category="guide"><div class="family-product-art" aria-hidden="true">◉</div><div><span class="tag">Curated guide</span><span class="tag"><?php echo esc_html( $evidence['status'] ); ?></span><h2><?php echo esc_html( get_the_title( $guide_id ) ); ?></h2><p><?php echo esc_html( wp_trim_words( get_the_excerpt( $guide_id ), 28 ) ); ?></p><div class="spec-grid"><span>Evidence <b><?php echo esc_html( $evidence['status'] ); ?></b></span><span>Last reviewed <b><?php echo esc_html( $evidence['last_reviewed'] ? $evidence['last_reviewed'] : 'Not set' ); ?></b></span></div><div class="buy-box"><strong>Continue the research path</strong><a class="button button-secondary" href="<?php echo esc_url( get_permalink( $guide_id ) ); ?>">Read guide</a><a class="button button-secondary" href="<?php echo esc_url( home_url( '/smart-tech-comparison/' ) ); ?>">Open comparison</a></div></div></article>
          <?php endforeach; ?>
        <?php else : ?>
        <article class="family-product-card" data-product-tags="all vacuum" data-product-category="vacuum" data-merchants="chewy amazon"><div class="family-product-art">◉</div><div><span class="tag">Comparison fixture</span><span class="tag">Research-led</span><h2>Roborock Q Revo MaxV</h2><p>Fixture for heavy shedding, mixed floors, and households that value automated dock work.</p><div class="spec-grid"><span>ScoutScore <b>Pending test record</b></span><span>Floor fit <b>Mixed</b></span><span>Evidence <b>Research-led</b></span><span>Merchant <b>Pending</b></span></div><div class="buy-box"><strong>Partner price pathway</strong><button type="button" disabled aria-disabled="true">Merchant pending</button><button type="button" disabled aria-disabled="true">Merchant pending</button><a class="button button-secondary" href="/smart-tech-comparison/">Open comparison</a><a class="button button-secondary" href="/pet-tech-selector/">Use selector</a></div></div></article>
        <article class="family-product-card" data-product-tags="all camera" data-product-category="camera" data-merchants="amazon"><div class="family-product-art">◍</div><div><span class="tag">Pet monitoring</span><h2>Furbo 360 Dog Camera</h2><p>Fixture for remote check-ins, alerts, and visibility between routines.</p></div></article>
        <?php endif; ?>
      </div>
    </div>
  </div></section>
  <section class="section"><div class="container trust-section-inline"><span class="dashicons dashicons-networking"></span><div><h2>Continue the decision path.</h2><p>Move from the hub to the comparison, selector, and evidence rules before any merchant pathway goes live.</p><div class="button-row"><a class="button button-secondary" href="/smart-tech-comparison/">Open comparison</a><a class="button button-secondary" href="/pet-tech-selector/">Use selector</a><a class="button button-secondary" href="/how-we-test/">Review evidence rules</a></div></div></div></section>
</main>
<?php get_footer(); ?>
