<?php get_header(); $hub = pethomescout_hub_values( 'Family Home', 'Pet-Friendly Family Home & Safety', 'Research-led guidance for pet-friendly fabrics, durable sofas, flooring considerations, and auto-closing dog gates.' ); $featured_products = pethomescout_hub_products( get_the_ID() ); $featured_guides = pethomescout_editorial_field( 'featured_guides', get_the_ID(), array() ); $featured_guides = is_array( $featured_guides ) ? array_filter( array_map( 'absint', $featured_guides ) ) : array(); ?>
<main class="hub-page">
  <section class="hub-hero"><div class="container"><span class="eyebrow"><?php echo esc_html( $hub['eyebrow'] ); ?></span><h1><?php echo esc_html( $hub['title'] ); ?></h1><p><?php echo esc_html( $hub['intro'] ); ?></p><div class="affiliate-disclosure-box"><strong>Affiliate disclosure:</strong> Merchant buttons remain disabled until approved partner destinations are configured. PetHomeScout may earn compensation when approved commercial links go live.</div></div></section>
  <section class="section"><div class="container">
    <div class="filter-bar" data-hub-filter><button class="is-active" type="button" data-filter="all">All home products</button><button type="button" data-filter="furniture">Claw-proof sofas</button><button type="button" data-filter="flooring">Wood flooring</button><button type="button" data-filter="safety">Dog gates &amp; safety</button><button type="button" data-filter="crate">Smart crate systems</button></div>
    <div class="family-home-layout"><aside class="filter-panel"><div class="filter-panel-heading"><h2>Filter options</h2><button type="button" class="filter-clear" data-filter-clear>Clear</button></div><div class="filter-section"><h3>Category</h3><label><input type="checkbox" value="furniture" data-filter-category checked> Furniture</label><label><input type="checkbox" value="safety" data-filter-category checked> Safety gates</label><label><input type="checkbox" value="flooring" data-filter-category> Flooring</label></div><div class="filter-section"><h3>Merchant options</h3><label><input type="checkbox" value="chewy" data-filter-merchant> Chewy</label><label><input type="checkbox" value="wayfair" data-filter-merchant> Wayfair</label><label><input type="checkbox" value="amazon" data-filter-merchant> Amazon</label></div></aside>
      <div><div class="section-label"><span>Recommended family home gear</span></div>
        <?php if ( ! empty( $featured_products ) ) : foreach ( $featured_products as $product_id ) : get_template_part( 'template-parts/cards/hub-product', null, array( 'product_id' => $product_id, 'icon' => '▱', 'comparison_url' => home_url( '/cleaning-odor/' ), 'service_url' => home_url( '/services-insurance/' ) ) ); endforeach; elseif ( ! empty( $featured_guides ) ) : foreach ( $featured_guides as $guide_id ) : $guide = get_post( $guide_id ); if ( ! $guide ) { continue; } $evidence = pethomescout_get_product_evidence( $guide_id ); ?>
          <article class="family-product-card" data-product-tags="all" data-product-category="guide"><div class="family-product-art" aria-hidden="true">▱</div><div><span class="tag">Curated guide</span><span class="tag"><?php echo esc_html( $evidence['status'] ); ?></span><h2><?php echo esc_html( get_the_title( $guide_id ) ); ?></h2><p><?php echo esc_html( wp_trim_words( get_the_excerpt( $guide_id ), 28 ) ); ?></p><div class="spec-grid"><span>Evidence <b><?php echo esc_html( $evidence['status'] ); ?></b></span><span>Last reviewed <b><?php echo esc_html( $evidence['last_reviewed'] ? $evidence['last_reviewed'] : 'Not set' ); ?></b></span></div><div class="buy-box"><strong>Continue the research path</strong><a class="button button-secondary" href="<?php echo esc_url( get_permalink( $guide_id ) ); ?>">Read guide</a><a class="button button-secondary" href="<?php echo esc_url( home_url( '/services-insurance/' ) ); ?>">Explore service path</a></div></div></article>
        <?php endforeach; else : ?>
        <article class="family-product-card" data-product-tags="all furniture" data-product-category="furniture" data-merchants="chewy wayfair amazon"><div class="family-product-art">▱</div><div><span class="tag">Research-led</span><span class="tag">Pet-friendly fabric</span><h2>Haven Claw-Resistant Velvet Sofa</h2><p>Research-led fixture based on published material specifications and care requirements. Scratch-resistance has not been independently verified.</p><div class="spec-grid"><span>Material <b>Double-weave velvet</b></span><span>Scratch evidence <b>Not independently verified</b></span><span>Sofa length <b>84 inches</b></span><span>Evidence <b>Research-led</b></span></div><div class="buy-box"><strong>Partner availability</strong><button type="button" disabled aria-disabled="true">Chewy&nbsp; Merchant pending</button><button type="button" disabled aria-disabled="true">Wayfair&nbsp; Merchant pending</button><button type="button" disabled aria-disabled="true">Amazon&nbsp; Merchant pending</button></div></div></article>
        <article class="family-product-card" data-product-tags="all safety" data-product-category="safety" data-merchants="chewy wayfair amazon"><div class="family-product-art">⌂</div><div><span class="tag">Safety pick</span><span class="tag">Pet-friendly entry</span><h2>Walk-Through Steel Safety Dog Gate</h2><p>Pressure-mounted gate fixture for separating pet zones while keeping everyday family movement simple.</p><div class="spec-grid"><span>Width range <b>29–39 inches</b></span><span>Lock type <b>One-hand latch</b></span><span>Finish <b>Powder-coated steel</b></span><span>Evidence <b>Research-led</b></span></div><div class="buy-box"><strong>Partner availability</strong><button type="button" disabled aria-disabled="true">Chewy&nbsp; Merchant pending</button><button type="button" disabled aria-disabled="true">Wayfair&nbsp; Merchant pending</button><button type="button" disabled aria-disabled="true">Amazon&nbsp; Merchant pending</button></div></div></article>
        <?php endif; ?>
      </div>
    </div>
  </div></section>
  <section class="section"><div class="container trust-section-inline"><span class="dashicons dashicons-admin-home"></span><div><h2>Connect home products to real household decisions.</h2><p>Compare safety, cleaning, and service paths before treating any product fixture as a final recommendation.</p><div class="button-row"><a class="button button-secondary" href="/cleaning-odor/">Cleaning &amp; odor hub</a><a class="button button-secondary" href="/services-insurance/">Service decision hub</a><a class="button button-secondary" href="/how-we-test/">Review evidence rules</a></div></div></div></section>
</main>
<?php get_footer(); ?>
