<?php get_header(); $hub = pethomescout_hub_values( 'Cleaning & odor', 'Pet Cleaning, Stains & Odor Control Hub', 'Compare carpet washers, enzyme-cleaning workflows, and air purification for homes with dogs, cats, and everyday mess.' ); $featured_products = pethomescout_hub_products( get_the_ID() ); $featured_guides = pethomescout_editorial_field( 'featured_guides', get_the_ID(), array() ); $featured_guides = is_array( $featured_guides ) ? array_filter( array_map( 'absint', $featured_guides ) ) : array(); ?>
<main class="hub-page">
  <section class="hub-hero"><div class="container"><span class="eyebrow"><?php echo esc_html( $hub['eyebrow'] ); ?></span><h1><?php echo esc_html( $hub['title'] ); ?></h1><p><?php echo esc_html( $hub['intro'] ); ?></p><div class="affiliate-disclosure-box"><strong>Affiliate disclosure:</strong> Merchant buttons remain disabled until approved partner destinations are configured. PetHomeScout may earn compensation when approved commercial links go live.</div></div></section>
  <section class="section"><div class="container">
    <div class="filter-bar" data-hub-filter><button class="is-active" type="button" data-filter="all">All cleaning gear</button><button type="button" data-filter="carpet">Carpet washers</button><button type="button" data-filter="air">Air purifiers</button><button type="button" data-filter="odor">Odor control</button></div>
    <div class="family-home-layout"><aside class="filter-panel"><h2>Filter options</h2><label><input type="checkbox" value="carpet" data-filter-category checked> Carpet care</label><label><input type="checkbox" value="air" data-filter-category checked> Air quality</label><label><input type="checkbox" value="odor" data-filter-category> Enzyme cleaners</label><label><input type="checkbox" value="chewy" data-filter-merchant> Chewy</label><label><input type="checkbox" value="amazon" data-filter-merchant> Amazon</label></aside>
      <div><div class="section-label"><span>Recommended cleaning &amp; odor gear</span></div>
        <?php if ( ! empty( $featured_products ) ) : foreach ( $featured_products as $product_id ) : get_template_part( 'template-parts/cards/hub-product', null, array( 'product_id' => $product_id, 'icon' => '◌', 'comparison_url' => home_url( '/cleaning-odor/' ), 'service_url' => home_url( '/pet-odor-carpet-cleaning/' ) ) ); endforeach; elseif ( ! empty( $featured_guides ) ) : foreach ( $featured_guides as $guide_id ) : $guide = get_post( $guide_id ); if ( ! $guide ) { continue; } $evidence = pethomescout_get_product_evidence( $guide_id ); ?>
          <article class="family-product-card" data-product-tags="all" data-product-category="guide"><div class="family-product-art" aria-hidden="true">◌</div><div><span class="tag">Curated guide</span><span class="tag"><?php echo esc_html( $evidence['status'] ); ?></span><h2><?php echo esc_html( get_the_title( $guide_id ) ); ?></h2><p><?php echo esc_html( wp_trim_words( get_the_excerpt( $guide_id ), 28 ) ); ?></p><div class="spec-grid"><span>Evidence <b><?php echo esc_html( $evidence['status'] ); ?></b></span><span>Last reviewed <b><?php echo esc_html( $evidence['last_reviewed'] ? $evidence['last_reviewed'] : 'Not set' ); ?></b></span></div><div class="buy-box"><strong>Continue the research path</strong><a class="button button-secondary" href="<?php echo esc_url( get_permalink( $guide_id ) ); ?>">Read guide</a><a class="button button-secondary" href="<?php echo esc_url( home_url( '/pet-odor-carpet-cleaning/' ) ); ?>">Explore service path</a></div></div></article>
        <?php endforeach; else : ?>
        <article class="family-product-card" data-product-tags="all carpet odor" data-product-category="carpet" data-merchants="chewy amazon"><div class="family-product-art">◌</div><div><span class="tag">Research fixture</span><span class="tag">Pet stain care</span><h2>Bissell SpotClean Pet Pro Carpet Washer</h2><p>Research-led fixture for spot treatment, upholstery cleanup, and recurring pet accidents.</p><div class="spec-grid"><span>Best for <b>Spot cleanup</b></span><span>Evidence <b>Research-led</b></span><span>Ownership <b>Rinse after use</b></span><span>Commercial action <b>Disabled</b></span></div><div class="buy-box"><strong>Compare partner prices</strong><button type="button" disabled aria-disabled="true">Merchant pending</button><button type="button" disabled aria-disabled="true">Merchant pending</button></div></div></article>
        <article class="family-product-card" data-product-tags="all air" data-product-category="air" data-merchants="amazon"><div class="family-product-art">◎</div><div><span class="tag">Air quality</span><h2>Levoit Pet True HEPA Air Purifier</h2><p>Fixture for homes prioritizing dander, airborne particles, and filter replacement visibility.</p></div></article>
        <?php endif; ?>
      </div>
    </div>
  </div></section>
  <section class="section"><div class="container trust-section-inline"><span class="dashicons dashicons-admin-tools"></span><div><h2>Choose product path or service path.</h2><p>Cleaning decisions often split between DIY products and professional pet-odor help. Use the problem guide and service demo before sharing personal information.</p><div class="button-row"><a class="button button-secondary" href="/pet-odor-carpet-cleaning/">Open odor guide</a><a class="button button-secondary" href="/services-insurance/">Preview service hub</a><a class="button button-secondary" href="/how-we-test/">Review evidence rules</a></div></div></div></section>
</main>
<?php get_footer(); ?>
